In [2]:
import tensorflow as tf
import numpy as np


In [2]:
def test_cross_entropy():
    t = tf.Variable([1,0,0,0,0], dtype=tf.float32)
    l = tf.Variable([1,0,0,0,0], dtype=tf.float32)
    
    s = tf.nn.softmax(t)
    y = tf.nn.softmax_cross_entropy_with_logits(labels=s, logits=s)
    sess = tf.Session()
    sess.run(tf.global_variables_initializer())
    
    print ("s={}".format(sess.run(s)))
    print (sess.run(y))
    
test_cross_entropy()


s=[ 0.40460971  0.14884759  0.14884759  0.14884759  0.14884759]
1.56261


In [3]:
def test_softmax():
    
    t_arr = np.array([[1,0,0,0], [1,0,0,0]])
    print ("t_arr.shape is {}".format(t_arr.shape))
    t = tf.Variable(np.array(t_arr), dtype=tf.float32)
   
    
    s1 = tf.nn.softmax(t) # Softmax on last dimension
    s2 = tf.nn.softmax(t, dim=0) 
    s3 = tf.nn.softmax(t, dim=1)
    #y = tf.nn.softmax_cross_entropy_with_logits(labels=s, logits=s)
    sess = tf.Session()
    sess.run(tf.global_variables_initializer())
    
    print ("s1={}, shape {}".format(sess.run(s1), sess.run(s1).shape))
    print ("s2={}, shape {}".format(sess.run(s2), sess.run(s2).shape))
    print ("s3={}, shape {}".format(sess.run(s3), sess.run(s3).shape))
    
    
test_softmax()

t_arr.shape is (2, 4)
s1=[[ 0.47536692  0.17487772  0.17487772  0.17487772]
 [ 0.47536692  0.17487772  0.17487772  0.17487772]], shape (2, 4)
s2=[[ 0.5  0.5  0.5  0.5]
 [ 0.5  0.5  0.5  0.5]], shape (2, 4)
s3=[[ 0.47536692  0.17487772  0.17487772  0.17487772]
 [ 0.47536692  0.17487772  0.17487772  0.17487772]], shape (2, 4)


In [5]:
def test_reduce_mean():
    logits = tf.Variable(np.arange(12).reshape([3,4]), dtype=tf.float32)
    s1 = tf.reduce_mean(logits) # shape (). Collapses all axes
    s2 = tf.reduce_mean(logits, axis=0) # shape (4,)
    s3 = tf.reduce_mean(logits, axis=1) # shape (3,)
    sess = tf.Session()
    sess.run(tf.global_variables_initializer())
    
    print ("s1={}".format(sess.run(s1)))
    print ("s2={}".format(sess.run(s2)))
    print ("s3={}".format(sess.run(s3)))
    
test_reduce_mean()

s1=5.5
s2=[ 4.          5.          6.          7.00000048]
s3=[ 1.5  5.5  9.5]


In [6]:
def test_split():
    inputs = tf.Variable(np.arange(12).reshape([3,4]), dtype=tf.float32)
    seq_length = 3
    ts = []
    xs = []
    split_result = tf.split(inputs, seq_length, axis=0)
    for t, xs_t in enumerate(split_result):
        ts.append(t)
        xs.append(xs_t)
        
    sess = tf.Session()
    sess.run(tf.global_variables_initializer())
    
    print ("inputs is {}, shape {}".format(sess.run(inputs), sess.run(inputs).shape))
    for i in ts:
        print ("xs[{}]={}".format(ts[i], sess.run(xs[i])))
    
    
    
test_split()

inputs is [[  0.   1.   2.   3.]
 [  4.   5.   6.   7.]
 [  8.   9.  10.  11.]], shape (3, 4)
xs[0]=[[ 0.  1.  2.  3.]]
xs[1]=[[ 4.  5.  6.  7.]]
xs[2]=[[  8.   9.  10.  11.]]


In [7]:
import os
os.getcwd()

'/media/zining/OS/Zining_Zhu/Programs/TA_Hackathon/RNN'

In [8]:
dir(tf)
# When cuDNN was not properly installed, dir(tf) looks like this

['__doc__', '__loader__', '__name__', '__package__', '__path__', '__spec__']

In [9]:
tf.__version__
# and tf.__version__ looks like this

AttributeError: module 'tensorflow' has no attribute '__version__'

In [7]:
dir(tf)

['AggregationMethod',
 'Assert',
 'AttrValue',
 'COMPILER_VERSION',
 'ConditionalAccumulator',
 'ConditionalAccumulatorBase',
 'ConfigProto',
 'DType',
 'DeviceSpec',
 'Dimension',
 'Event',
 'FIFOQueue',
 'FixedLenFeature',
 'FixedLenSequenceFeature',
 'FixedLengthRecordReader',
 'GIT_VERSION',
 'GPUOptions',
 'GRAPH_DEF_VERSION',
 'GRAPH_DEF_VERSION_MIN_CONSUMER',
 'GRAPH_DEF_VERSION_MIN_PRODUCER',
 'Graph',
 'GraphDef',
 'GraphKeys',
 'GraphOptions',
 'HistogramProto',
 'IdentityReader',
 'IndexedSlices',
 'InteractiveSession',
 'LogMessage',
 'MetaGraphDef',
 'NameAttrList',
 'NoGradient',
 'NodeDef',
 'NotDifferentiable',
 'OpError',
 'Operation',
 'OptimizerOptions',
 'PaddingFIFOQueue',
 'Print',
 'PriorityQueue',
 'QUANTIZED_DTYPES',
 'QueueBase',
 'RandomShuffleQueue',
 'ReaderBase',
 'RegisterGradient',
 'RunMetadata',
 'RunOptions',
 'Session',
 'SessionLog',
 'SparseConditionalAccumulator',
 'SparseFeature',
 'SparseTensor',
 'SparseTensorValue',
 'Summary',
 'TFRecordReade

In [8]:
tf.__version__

'1.2.1'

In [5]:
def test_tf_concat():
    print ("Testing shapes of tf.concat!")
    x = tf.Variable(np.arange(12).reshape([3,4]), dtype=tf.float32)
    y = tf.Variable(np.arange(12).reshape([3,4]), dtype=tf.float32)
    
    sess = tf.Session()
    sess.run(tf.global_variables_initializer())
    
    
    print (sess.run(tf.concat([x, y], axis=0)).shape)
    print (sess.run(tf.concat([x, y], axis=1)).shape)
    
test_tf_concat()

Testing shapes of tf.concat!
(6, 4)
(3, 8)


In [8]:
def test_tf_broadcast():
    Wx = tf.Variable(np.arange(12).reshape([3,4]), dtype=tf.float32)
    b1 = tf.ones([3,1])
    b2 = tf.ones([1,4])
    
    sess = tf.Session()
    sess.run(tf.global_variables_initializer())
    
    print (sess.run(Wx + b1))
    print (sess.run(Wx + b2))
    
test_tf_broadcast()

[[  1.   2.   3.   4.]
 [  5.   6.   7.   8.]
 [  9.  10.  11.  12.]]
[[  1.   2.   3.   4.]
 [  5.   6.   7.   8.]
 [  9.  10.  11.  12.]]


In [12]:
def _const(shape, dtype):
    
    d1 = shape[0]
    d2 = shape[1]
    tmp = np.zeros(shape=shape)
    
    tmp[:, 0] = np.ones(shape=[d1,])
    return tf.constant(tmp, dtype=dtype)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
b = _const([2,5], tf.float32)
print (sess.run(b))

[[ 1.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.]]


In [19]:
def test_elementwise_mult():
    x = tf.Variable(np.arange(6).reshape([2,1,3]))
    y = tf.Variable(np.arange(6).reshape([2,1,3])) # x and y has to be of the same shape
    m1 = tf.multiply(x, y)
    m2 = x * y
    
    sess = tf.Session()
    sess.run(tf.global_variables_initializer())
    
    res1 = sess.run(m1)
    print (res1)
    print ("shape is {}\n".format(res1.shape))
    res2 = sess.run(m2)
    print (res2)
    print ("shape is {}\n".format(res2.shape))
    
    
test_elementwise_mult()

[[[ 0  1  4]]

 [[ 9 16 25]]]
shape is (2, 1, 3)

[[[ 0  1  4]]

 [[ 9 16 25]]]
shape is (2, 1, 3)



In [3]:
def test_random_choice():
    return np.random.choice(4, 1, np.array([0.25] * 4).reshape([1,4]))
    
test_random_choice()

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()