In [2]:
import tensorflow as tf
import numpy as np


In [9]:
def test_cross_entropy():
    t = tf.Variable([1,0,0,0,0], dtype=tf.float32)
    l = tf.Variable([1,0,0,0,0], dtype=tf.float32)
    
    s = tf.nn.softmax(t)
    y = tf.nn.softmax_cross_entropy_with_logits(labels=s, logits=s)
    sess = tf.Session()
    sess.run(tf.global_variables_initializer())
    
    print ("s={}".format(sess.run(s)))
    print (sess.run(y))
    
test_cross_entropy()


s=[ 0.40460971  0.14884759  0.14884759  0.14884759  0.14884759]
1.56261


In [3]:
def test_softmax():
    
    t_arr = np.array([[1,0,0,0], [1,0,0,0]])
    print ("t_arr.shape is {}".format(t_arr.shape))
    t = tf.Variable(np.array(t_arr), dtype=tf.float32)
   
    
    s1 = tf.nn.softmax(t) # Softmax on last dimension
    s2 = tf.nn.softmax(t, dim=0) 
    s3 = tf.nn.softmax(t, dim=1)
    #y = tf.nn.softmax_cross_entropy_with_logits(labels=s, logits=s)
    sess = tf.Session()
    sess.run(tf.global_variables_initializer())
    
    print ("s1={}, shape {}".format(sess.run(s1), sess.run(s1).shape))
    print ("s2={}, shape {}".format(sess.run(s2), sess.run(s2).shape))
    print ("s3={}, shape {}".format(sess.run(s3), sess.run(s3).shape))
    
    
test_softmax()

t_arr.shape is (2, 4)
s1=[[ 0.47536692  0.17487772  0.17487772  0.17487772]
 [ 0.47536692  0.17487772  0.17487772  0.17487772]], shape (2, 4)
s2=[[ 0.5  0.5  0.5  0.5]
 [ 0.5  0.5  0.5  0.5]], shape (2, 4)
s3=[[ 0.47536692  0.17487772  0.17487772  0.17487772]
 [ 0.47536692  0.17487772  0.17487772  0.17487772]], shape (2, 4)


In [6]:
def test_reduce_mean():
    logits = tf.Variable(np.arange(12).reshape([3,4]), dtype=tf.float32)
    s1 = tf.reduce_mean(logits) # shape (). Collapses all axes
    s2 = tf.reduce_mean(logits, axis=0) # shape (4,)
    s3 = tf.reduce_mean(logits, axis=1) # shape (3,)
    sess = tf.Session()
    sess.run(tf.global_variables_initializer())
    
    print ("s1={}".format(sess.run(s1)))
    print ("s2={}".format(sess.run(s2)))
    print ("s3={}".format(sess.run(s3)))
    
test_reduce_sum()

s1=66.0
s2=[ 12.  15.  18.  21.]
s3=[  6.  22.  38.]


In [7]:
def test_split():
    inputs = tf.Variable(np.arange(12).reshape([3,4]), dtype=tf.float32)
    seq_length = 3
    ts = []
    xs = []
    split_result = tf.split(inputs, seq_length, axis=0)
    for t, xs_t in enumerate(split_result):
        ts.append(t)
        xs.append(xs_t)
        
    sess = tf.Session()
    sess.run(tf.global_variables_initializer())
    
    print ("inputs is {}, shape {}".format(sess.run(inputs), sess.run(inputs).shape))
    for i in ts:
        print ("xs[{}]={}".format(ts[i], sess.run(xs[i])))
    
    
    
test_split()

inputs is [[  0.   1.   2.   3.]
 [  4.   5.   6.   7.]
 [  8.   9.  10.  11.]], shape (3, 4)
xs[0]=[[ 0.  1.  2.  3.]]
xs[1]=[[ 4.  5.  6.  7.]]
xs[2]=[[  8.   9.  10.  11.]]
